modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/evailcodes/ChainTogether/issues"

[[mods]]
modId="chaintogether"
version="${mod_version}"
displayName="Chain Together"
description="A mod that chains players together with configurable chain mechanics!"
authors="DY_XiaoJiaZi"
logoFile="chain_icon.png"
credits="Inspired by Steam's 'Chain Together'"

[[dependencies.chaintogether]]
modId="forge"
mandatory=true
versionRange="[47.4.13,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaintogether]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"